#!/bin/sh

if test -e "$HOME/.config/hedlund/firstboot-done"; then
  echo "Already ran"
  exit 0
fi

# zerr reports a zenity error, and then exists the script.
zerr() {
  zenity --error --text="$1"
  exit 1
}

# finstall installs a flatpak from flathub in user space, or dies trying.
finstall() {
  echo "# Installing $3"
  /usr/bin/flatpak install --user --noninteractive flathub $2
  if [ "$?" != 0 ]; then
    zerr "Installing $3 Failed"
  fi
  echo "$1"
}

(
echo "# Waiting For Internet Connection"
until /usr/bin/ping -q -c 1 flathub.org; do sleep 1; done
echo "00"

echo "# Removing Filtered Flathub Repository"
/usr/bin/flatpak remote-delete flathub --force ||:
if [ "$?" != 0 ] ; then
  zerr "Removing Filtered Flathub Repo Failed"
fi
echo "3"

echo "# Adding Flathub Repository"
/usr/bin/flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
if [ "$?" != 0 ] ; then
  zerr "Adding Flathub Repository Failed"
fi
echo "5"

echo "# Replacing Fedora Flatpaks with Flathub Ones (this may take a while)"
/usr/bin/flatpak install --user --noninteractive org.gnome.Platform//43
/usr/bin/flatpak install --user --noninteractive --reinstall flathub $(flatpak list --app-runtime=org.fedoraproject.Platform --columns=application | tail -n +1 )
if [ "$?" != 0 ] ; then
  zerr "Replacing Fedora Flatpaks Failed"
fi
echo "20"

echo "Removing All Preinstalled Flatpaks"
/usr/bin/flatpak remove --system --noninteractive --all ||:
if [ "$?" != 0 ] ; then
  zerr "Removing All Preinstalled Flatpaks Failed"
fi

echo "# Removing Fedora Flatpak Repository"
/usr/bin/flatpak remote-delete fedora --force ||:
if [ "$?" != 0 ] ; then
  zerr "Removing Fedora Flatpak Repo Failed"
fi
echo "25"

# Install new flatpak apps...
finstall 30 com.raggesilver.BlackBox "Black Box"
finstall 40 org.cubocore.CoreShot "CoreShot"
finstall 50 com.mattjakeman.ExtensionManager "Extension Manager"
#finstall 60 org.mozilla.firefox "Firefox"
finstall 70 org.gustavoperedo.FontDownloader "Font Downloader"
finstall 80 com.github.tchx84.Flatseal "Flatseal"
finstall 90 com.mastermindzh.tidal-hifi "Tidal"

echo "# Installing 1Password"
/usr/bin/flatpak install --user --noninteractive https://downloads.1password.com/linux/flatpak/1Password.flatpakref
if [ "$?" != 0 ]; then
  zerr "Installing 1Password Failed"
fi
echo "95"

# We cannot modify the kernel arguments when building the OCI image, so we'll
# have to delay it to here. First check if we actually have the nvidia driver
# installed.
if [[ "$(/usr/bin/rpm-ostree status --booted)" =~ "akmod-nvidia" ]]; then
  echo "# Fixing Nvidia Driver (Disabling Nouveau)"
  # This might not be needed in the future:
  # https://rpmfusion.org/Howto/NVIDIA#OSTree_.28Silverblue.2FKinoite.2Fetc.29
  if [[ ! "$(/usr/bin/rpm-ostree kargs)" =~ "blacklist=nouveau" ]]; then
    sudo /usr/bin/rpm-ostree kargs --append=rd.driver.blacklist=nouveau --append=modprobe.blacklist=nouveau --append=nvidia-drm.modeset=1
    if [ "$?" != 0 ]; then
      zerr "Disabling Nouveau Failed"
    fi
  fi
fi
echo "100"

echo "# Wrapping Up"
mkdir -p "$HOME/.config/hedlund/"
touch "$HOME/.config/hedlund/firstboot-done"

) | zenity --progress --title="Hedlund SilverBlue FirstBoot" --percentage=0 --auto-close --no-cancel --width=300

if [ "$?" != 0 ]; then
  zerr "FirstBoot Configuration Error"
fi
